package ricbot.domain.runtime;

public enum RuntimeFaultPoint {
    AFTER_EVENT_BEFORE_PROJECTION,
    AFTER_PROJECTION_BEFORE_COMMIT,
    AFTER_TASK_RESULT_BEFORE_DELIVERY,
    AFTER_DELIVERY_BEFORE_COMMIT,
    AFTER_SIGNAL_BEFORE_COMMIT
}
